
# DATABASES ################################################################
# REDASH -------------------------------------------------------------------
databases:
  - name: redash
    region: frankfurt
    databaseName: redash
    user: redash

# SERVICES #################################################################
# PROMETHEUS ---------------------------------------------------------------
# web | docker
services:
  - type: web
    name: prometheus
    env: docker
    dockerfilePath: ./prometheus/Dockerfile
    region: frankfurt
    plan: starter
    branch: main
    disk:
      name: data
      mountPath: /prometheus
      sizeGB: 20
    buildFilter:
      paths:
      - prometheus/**

# TAILSCALE -----------------------------------------------------------
# web | docker
  - type: web
    name: render-subnet-router
    env: docker
    region: frankfurt
    plan: starter
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: 1.26.1
      - key: ADVERTISE_ROUTES
        value: 10.0.0.0/8
    disk:
      name: tailscale-state
      mountPath: /var/lib/tailscale
      sizeGB: 1

# REDASH ---------------------------------------------------------------
# web | docker
# Do not forget to run `render-redash create_db` in Render Shell after 
# creating this service.
  - type: web
    name: redash
    env: docker
    dockerfilePath: ./redash/Dockerfile
    region: frankfurt
    plan: standard
    dockerCommand: ./redash/render-redash server
    envVars:
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash
          property: connectionString
      - key: REDIS_HOSTPORT
        fromService:
          type: pserv
          name: redash-redis
          property: hostport
      - fromGroup: redash-shared
      - fromGroup: redash-mail
    buildFilter:
      paths:
      - redash/**

# worker | docker
  - type: worker
    name: redash-scheduler
    env: docker
    dockerfilePath: ./redash/Dockerfile
    dockerCommand: ./redash/render-redash scheduler
    region: frankfurt
    envVars:
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash
          property: connectionString
      - key: REDIS_HOSTPORT
        fromService:
          type: pserv
          name: redash-redis
          property: hostport
      - fromGroup: redash-shared
      - fromGroup: redash-mail
      - key: QUEUES
        value: "celery"
      - key: WORKERS_COUNT
        value: 1
    buildFilter:
      paths:
      - redash/**

# worker | docker
  - type: worker
    name: redash-worker
    env: docker
    plan: standard
    region: frankfurt
    dockerfilePath: ./redash/Dockerfile
    dockerCommand: ./redash/render-redash worker
    envVars:
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash
          property: connectionString
      - key: REDIS_HOSTPORT
        fromService:
          type: pserv
          name: redash-redis
          property: hostport
      - fromGroup: redash-shared
      - fromGroup: redash-mail
      - key: QUEUES
        value: "queries,scheduled_queries,schemas"
    buildFilter:
      paths:
      - redash/**

# private | docker
  - type: pserv
    name: redash-redis
    env: docker
    repo: https://github.com/render-examples/redis.git
    region: frankfurt
    disk:
      name: data
      mountPath: /var/lib/redis
      sizeGB: 10
    buildFilter:
      paths:
      - redash/**

# ENVIRONMENT VARIABLES GROUP ##############################################
# REDASH-SHARED ------------------------------------------------------------
envVarGroups:
  - name: redash-shared
    envVars:
      - key: REDASH_LOG_LEVEL
        value: "INFO"
      - key: REDASH_COOKIE_SECRET
        generateValue: true

# Uncomment and fill following fields if you wish to set up mailing in Redash.
# It’s recommended to use some mail service, like Amazon SES or Mailgun
# to send emails to ensure deliverability.
  - name: redash-mail
    envVars:
#      - key: REDASH_MAIL_SERVER
#        value: (SMTP server address)
#      - key: REDASH_MAIL_PORT
#        value: 25
#      - key: REDASH_MAIL_USE_TLS
#        value: false
#      - key: REDASH_MAIL_USE_SSL
#        value: false
#      - key: REDASH_MAIL_USERNAME
#        value: None
#      - key: REDASH_MAIL_PASSWORD
#        value: None
#      - key: REDASH_MAIL_DEFAULT_SENDER
#        value: (Email address to send from)